version: '2.1'
services:
  redis:
    image: 'redis:5.0.5'
    restart: always
    # command: redis-server --requirepass redispass

  postgres:
    image: postgres:12.0
    restart: always
    environment:
    - POSTGRES_USER=airflow
    - POSTGRES_PASSWORD=airflow
    - POSTGRES_DB=airflow
    # Uncomment these lines to persist data on the local filesystem.
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - /var/db/1/airflow-pg-data:/var/lib/postgresql/data/pgdata

  postgis:
    image: kartoza/postgis:12.0
    restart: always
    environment:
    - POSTGRES_USER=airflow
    - POSTGRES_PASSWORD=airflow
    - POSTGRES_DB=gis
#    - ALLOW_IP_RANGE
    # Uncomment these lines to persist data on the local filesystem.
    - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
    - 5432:5432
    volumes:
    - /var/db/1/airflow-postgis-data:/var/lib/postgresql/data/pgdata

  mongo:
    image: mongo:4.2.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
    - /var/db/1/airflow-mongo-data:/data/db

  mongo-express:
    image: mongo-express:0.49
    restart: always
    ports:
      - 8084:8084
    environment:
      VCAP_APP_PORT: 8084
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  webserver:
    image: puckel/docker-airflow:1.10.4
    restart: always
    depends_on:
    - postgres
    - redis
    environment:
    - LOAD_EX=n
    - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    - EXECUTOR=Celery
    - PYTHONPATH=/usr/local/airflow/dags
    # - POSTGRES_USER=airflow
    # - POSTGRES_PASSWORD=airflow
    # - POSTGRES_DB=airflow
    # - REDIS_PASSWORD=redispass
    volumes:
    - ./dags:/usr/local/airflow/dags
    - ./plugins:/usr/local/airflow/plugins
    - ../:/usr/local/airflow/ai
    ports:
    - "8083:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  flower:
    image: puckel/docker-airflow:1.10.4
    restart: always
    depends_on:
    - redis
    environment:
    - EXECUTOR=Celery
    # - REDIS_PASSWORD=redispass
    ports:
    - "5555:5555"
    command: flower

  scheduler:
    image: puckel/docker-airflow:1.10.4
    restart: always
    depends_on:
    - webserver
    volumes:
    - ./dags:/usr/local/airflow/dags
    - ./plugins:/usr/local/airflow/plugins
    - ../:/usr/local/airflow/ai
    # Uncomment to include custom plugins
    environment:
    - LOAD_EX=n
    - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    - EXECUTOR=Celery
    - PYTHONPATH=/usr/local/airflow/dags
    # - POSTGRES_USER=airflow
    # - POSTGRES_PASSWORD=airflow
    # - POSTGRES_DB=airflow
    # - REDIS_PASSWORD=redispass
    command: scheduler

  worker:
    image: puckel/docker-airflow:1.10.4
    restart: always
    depends_on:
    - scheduler
    volumes:
    - ./dags:/usr/local/airflow/dags
    - ./plugins:/usr/local/airflow/plugins
    - ../requirements.txt:/requirements.txt
    - ../:/usr/local/airflow/ai
    - /var/datasets/0:/var/datasets/0
    - /var/datasets/1:/var/datasets/1
    - /var/datasets/2:/var/datasets/2
    environment:
    - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    - EXECUTOR=Celery
    - PYTHONPATH=/usr/local/airflow/dags
    # - POSTGRES_USER=airflow
    # - POSTGRES_PASSWORD=airflow
    # - POSTGRES_DB=airflow
    # - REDIS_PASSWORD=redispass
    command: worker
